name = "12th MEU TCP"
prefix = "12thMEU"
author = "Sammy"
mainprefix = "x"

[files]
include = [
    "mod.cpp",
    "logo.paa",
    "README.md",
    "LICENSE",
    "*.pbo"
]

[version]
major = 0
minor = 0
patch = 0
build = 1
git_hash = 0